name: Makefile test

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential libreadline-dev gcc

      - name: Run Makefile
        run: make

      - name: Run make clean
        run: make clean

      - name: Run make fclean
        run: make fclean

      - name: Run make re
        run: make re